### ISSUE TITLE
Wrong key name with namespaced class 

### ISSUE THREAD

**Issue by takashi** [nateware/redis-objects#184] opened 2015-06-27 18:18 UTC
I tried to implement class with redis-objects like

```ruby
class Article::Pickup
  include Redis::Objects
  set :articles

  def id; 1 end
end
```

I expected to create redis key like `article::pickup:1:articles` but I got `pickup:1:articles` 

any solutions ?

**Comment by rossta** [comment] 2015-06-29 22:11
The behavior you're seeing is tied to the following implementation: https://github.com/nateware/redis-objects/blob/7bedb25e295dd1f3837021f342c98fd9b697dd2a/lib/redis/objects.rb#L108. 

You can override this to whatever you want with something like:

```ruby
class Article::Pickup
  include Redis::Objects

  # CAUTION: changing this value will orphan all 
  # current redis-persisted attributes for this prefix
  self.redis_prefix = 'article:pickup'

  set :articles

  def id; 1 end
end
```

**Comment by takashi** [comment] 2015-06-30 03:39
@rossta aha, i see! thanks.
but is it a correct behavior? if not, I'd like to send pull request for fixing this.

**Comment by rossta** [comment] 2015-06-30 08:53
I'm inclined to agree that this behavior is surprising. Changing it would require a coordinated upgrade path (deprecation warning, ability to keep "legacy" behavior, etc) since anyone currently using `redis-objects` with namespaced classes may be at risk at orphaning their redis object attributes.

**Comment by takashi** [comment] 2015-06-30 11:20
@rossta I totally agree with your opinion. I'll send  pull request for that later :)

**Comment by nateware** [comment] 2016-08-09 21:05
Unfortunately this is a lower-priority issue that breaks backwards compatibility, so marking as not to be fixed.  Can reopen if others feel differently.  While it can be considered a bug, it's also working as intended, even if the behavior is surprising.

**Closed by nateware** 2016-08-09 21:05 UTC
Labels: feature, parked
