### ISSUE TITLE
normal unordered sets are sorting by value

### ISSUE THREAD

**Issue by luckyraul** [nateware/redis-objects#167] opened 2015-01-25 12:46 UTC
It's said "Sets work like the Ruby Set class. They are unordered, but guarantee uniqueness of members."

```ruby
@set = Redis::Set.new('set_name')
@set << 3
@set.members
[
    [0] "3"
]
@set << 5
@set.members
[
    [0] "3",
    [1] "5"
]
```

but 
```ruby
@set << -4
@set.members
[
    [0] "-4",
    [1] "3",
    [2] "5"
]
@set << 1
@set.members
[
    [0] "-4",
    [1] "1",
    [2] "3",
    [3] "5"
]

```

May be I'am doing something wrong, but why they are ordered by value?

**Comment by luckyraul** [comment] 2015-01-25 12:50
nevertheless
```ruby
s=Set.new
[]
s << 3
[
    [0] 3
]
s << 2
[
    [0] 3,
    [1] 2
]
s << -5
[
    [0] 3,
    [1] 2,
    [2] -5
]
```

**Comment by nateware** [comment] 2015-02-16 20:34
I'm not sure what the issue is here.  Sometimes values may end up sorted as an artifact of the implementation.  Redis doesn't guarantee that normal sets are sorted, but it also doesn't guarantee that they're **NOT** sorted.  I'm going to close this out for now.

**Closed by nateware** 2015-02-16 20:34 UTC
